### ISSUE TITLE
Exception (EXC_BAD_ACCESS) when accessing vector in nested type object

### ISSUE THREAD

**Issue by adamski** [realm/realm-cpp#116] opened 2023-11-20 21:27 UTC
I have the following schema:

```cpp
struct TonalDBMapping
{
    bool                      customKeyMap = false;
    tonaldb::NoteLayout       noteLayout = tonaldb::NoteLayout::all;
    std::optional<int64_t>    referenceNote = std::nullopt;
    std::optional<double>     referenceFrequency = std::nullopt;
    std::optional<int64_t>    rootNote = std::nullopt;
    std::vector<realm::mixed> keyMap = { std::monostate() };
};
REALM_EMBEDDED_SCHEMA (TonalDBMapping, customKeyMap, noteLayout, referenceNote, referenceFrequency, rootNote, keyMap)

struct TonalDBTuning
{
    primary_key<realm::object_id> _id { realm::object_id::generate() };
    std::string                   title;
    std::string                   shortTitle;
    std::string                   description;
    std::string                   author;
    std::string                   period;
    std::vector<TonalDBPitch*>    pitches;
    TonalDBMapping*               mapping;
    // The ownerId property stores the user.identifier() of the logged-in user.
    std::string ownerId;
};
REALM_SCHEMA (TonalDBTuning, _id, title, shortTitle, description, author, period, pitches, mapping, ownerId)
```

When I call `add`:
```cpp
       syncedRealm->write ([&]
                                   { syncedRealm->add (std::move (newTuning)); });
    }
```

I am hitting a EXC_BAD_ACCESS crash. It seems to be to do with the std::variant i.e. the realm::mixed type. 

I'm on macOS Ventura, building with clang.

<img width="1108" alt="Screenshot 2023-11-20 at 21 23 02" src="https://github.com/realm/realm-cpp/assets/14980/b795aeaf-2544-4497-a7eb-3420214c9a2b">

<img width="1443" alt="Screenshot 2023-11-20 at 21 25 46" src="https://github.com/realm/realm-cpp/assets/14980/cea22493-c03a-4a79-a3e9-4e5acc106f04">

Here is the stack trace:
```
decltype(auto) std::__1::__variant_detail::__visitation::__base::__visit_alt_at[abi:v15006]<void std::__1::__variant_detail::__ctor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>>::__generic_construct[abi:v15006]<std::__1::__variant_detail::__copy_constructor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>, (std::__1::__variant_detail::_Trait)1> const&>(std::__1::__variant_detail::__ctor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>>&, std::__1::__variant_detail::__copy_constructor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>, (std::__1::__variant_detail::_Trait)1> const&)::'lambda'(std::__1::__variant_detail::__copy_constructor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>, (std::__1::__variant_detail::_Trait)1> const&, auto&&), std::__1::__variant_detail::__ctor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>>&, std::__1::__variant_detail::__copy_constructor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>, (std::__1::__variant_detail::_Trait)1> const&>(unsigned long, std::__1::__variant_detail::__copy_constructor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>, (std::__1::__variant_detail::_Trait)1> const&, std::__1::__variant_detail::__ctor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>>&, std::__1::__variant_detail::__copy_constructor<std::__1::__variant_detail::__traits<std::__1::monostate, long long, bool, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l>>>, realm::uuid, realm::object_id, realm::decimal128>, (std::__1::__variant_detail::_Trait)1> const&) variant:500
std::__variant_detail::__ctor::__generic_construct[abi:v15006]<…>(std::__variant_detail::__ctor<…> &, const std::__variant_detail::__copy_constructor<…> &) variant:898
std::__variant_detail::__copy_constructor::__copy_constructor(const std::__variant_detail::__copy_constructor<…> &) variant:977
std::__variant_detail::__assignment::__assignment(const std::__variant_detail::__assignment<…> &) variant:991
std::__variant_detail::__move_assignment::__move_assignment(const std::__variant_detail::__move_assignment<…> &) variant:1076
std::__variant_detail::__copy_assignment::__copy_assignment(const std::__variant_detail::__copy_assignment<…> &) variant:1117
std::__variant_detail::__impl::__impl(const std::__variant_detail::__impl<…> &) variant:1137
std::__variant_detail::__impl::__impl(const std::__variant_detail::__impl<…> &) variant:1137
std::variant::variant(const std::variant<…> &) variant:1305
std::variant::variant(const std::variant<…> &) variant:1305
realm::internal::bridge::obj::set_list_values<…>(const realm::internal::bridge::col_key &, const std::vector<…> &) obj.hpp:196
realm::experimental::accessor::set(realm::internal::bridge::obj &, realm::internal::bridge::col_key &&, const realm::internal::bridge::realm &, const std::vector<…> &) accessors.hpp:266
auto realm::experimental::accessor<TonalDBMapping*, void>::set(realm::internal::bridge::obj&, realm::internal::bridge::col_key&&, realm::internal::bridge::realm const&, TonalDBMapping*)::'lambda'(auto&&...)::operator()<realm::schemagen::property<&TonalDBMapping::customKeyMap, false> const&, realm::schemagen::property<&TonalDBMapping::noteLayout, false> const&, realm::schemagen::property<&TonalDBMapping::referenceNote, false> const&, realm::schemagen::property<&TonalDBMapping::referenceFrequency, false> const&, realm::schemagen::property<&TonalDBMapping::rootNote, false> const&, realm::schemagen::property<&TonalDBMapping::keyMap, false> const&>(auto&&...) const accessors.hpp:430
decltype(std::declval<realm::experimental::accessor<TonalDBMapping*, void>::set(realm::internal::bridge::obj&, realm::internal::bridge::col_key&&, realm::internal::bridge::realm const&, TonalDBMapping*)::'lambda'(auto&&...)>()(std::declval<realm::schemagen::property<&TonalDBMapping::customKeyMap, false> const&>(), std::declval<realm::schemagen::property<&TonalDBMapping::noteLayout, false> const&>(), std::declval<realm::schemagen::property<&TonalDBMapping::referenceNote, false> const&>(), std::declval<realm::schemagen::property<&TonalDBMapping::referenceFrequency, false> const&>(), std::declval<realm::schemagen::property<&TonalDBMapping::rootNote, false> const&>(), std::declval<realm::schemagen::property<&TonalDBMapping::keyMap, false> const&>())) std::__1::__invoke[abi:v15006]<realm::experimental::accessor<TonalDBMapping*, void>::set(realm::internal::bridge::obj&, realm::internal::bridge::col_key&&, realm::internal::bridge::realm const&, TonalDBMapping*)::'lambda'(auto&&...), realm::schemagen::property<&TonalDBMapping::customKeyMap, false> const&, realm::schemagen::property<&TonalDBMapping::noteLayout, false> const&, realm::schemagen::property<&TonalDBMapping::referenceNote, false> const&, realm::schemagen::property<&TonalDBMapping::referenceFrequency, false> const&, realm::schemagen::property<&TonalDBMapping::rootNote, false> const&, realm::schemagen::property<&TonalDBMapping::keyMap, false> const&>(realm::experimental::accessor<TonalDBMapping*, void>::set(realm::internal::bridge::obj&, realm::internal::bridge::col_key&&, realm::internal::bridge::realm const&, TonalDBMapping*)::'lambda'(auto&&...)&&, realm::schemagen::property<&TonalDBMapping::customKeyMap, false> const&, realm::schemagen::property<&TonalDBMapping::noteLayout, false> const&, realm::schemagen::property<&TonalDBMapping::referenceNote, false> const&, realm::schemagen::property<&TonalDBMapping::referenceFrequency, false> const&, realm::schemagen::property<&TonalDBMapping::rootNote, false> const&, realm::schemagen::property<&TonalDBMapping::keyMap, false> const&) invoke.h:394
decltype(auto) std::__1::__apply_tuple_impl[abi:v15006]<realm::experimental::accessor<TonalDBMapping*, void>::set(realm::internal::bridge::obj&, realm::internal::bridge::col_key&&, realm::internal::bridge::realm const&, TonalDBMapping*)::'lambda'(auto&&...), std::__1::tuple<realm::schemagen::property<&TonalDBMapping::customKeyMap, false>, realm::schemagen::property<&TonalDBMapping::noteLayout, false>, realm::schemagen::property<&TonalDBMapping::referenceNote, false>, realm::schemagen::property<&TonalDBMapping::referenceFrequency, false>, realm::schemagen::property<&TonalDBMapping::rootNote, false>, realm::schemagen::property<&TonalDBMapping::keyMap, false>> const&, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul>(realm::experimental::accessor<TonalDBMapping*, void>::set(realm::internal::bridge::obj&, realm::internal::bridge::col_key&&, realm::internal::bridge::realm const&, TonalDBMapping*)::'lambda'(auto&&...)&&, std::__1::tuple<realm::schemagen::property<&TonalDBMapping::customKeyMap, false>, realm::schemagen::property<&TonalDBMapping::noteLayout, false>, realm::schemagen::property<&TonalDBMapping::referenceNote, false>, realm::schemagen::property<&TonalDBMapping::referenceFrequency, false>, realm::schemagen::property<&TonalDBMapping::rootNote, false>, realm::schemagen::property<&TonalDBMapping::keyMap, false>> const&, std::__1::__tuple_indices<0ul, 1ul, 2ul, 3ul, 4ul, 5ul>) tuple:1789
decltype(auto) std::__1::apply[abi:v15006]<realm::experimental::accessor<TonalDBMapping*, void>::set(realm::internal::bridge::obj&, realm::internal::bridge::col_key&&, realm::internal::bridge::realm const&, TonalDBMapping*)::'lambda'(auto&&...), std::__1::tuple<realm::schemagen::property<&TonalDBMapping::customKeyMap, false>, realm::schemagen::property<&TonalDBMapping::noteLayout, false>, realm::schemagen::property<&TonalDBMapping::referenceNote, false>, realm::schemagen::property<&TonalDBMapping::referenceFrequency, false>, realm::schemagen::property<&TonalDBMapping::rootNote, false>, realm::schemagen::property<&TonalDBMapping::keyMap, false>> const&>(realm::experimental::accessor<TonalDBMapping*, void>::set(realm::internal::bridge::obj&, realm::internal::bridge::col_key&&, realm::internal::bridge::realm const&, TonalDBMapping*)::'lambda'(auto&&...)&&, std::__1::tuple<realm::schemagen::property<&TonalDBMapping::customKeyMap, false>, realm::schemagen::property<&TonalDBMapping::noteLayout, false>, realm::schemagen::property<&TonalDBMapping::referenceNote, false>, realm::schemagen::property<&TonalDBMapping::referenceFrequency, false>, realm::schemagen::property<&TonalDBMapping::rootNote, false>, realm::schemagen::property<&TonalDBMapping::keyMap, false>> const&) tuple:1798
realm::experimental::accessor::set(realm::internal::bridge::obj &, realm::internal::bridge::col_key &&, const realm::internal::bridge::realm &, TonalDBMapping *) accessors.hpp:429
auto realm::experimental::managed<std::__1::remove_const<TonalDBTuning>::type, void> realm::experimental::db::add<TonalDBTuning>(TonalDBTuning&&)::'lambda'(auto&&...)::operator()<realm::schemagen::property<&TonalDBTuning::_id, false> const&, realm::schemagen::property<&TonalDBTuning::title, false> const&, realm::schemagen::property<&TonalDBTuning::shortTitle, false> const&, realm::schemagen::property<&TonalDBTuning::description, false> const&, realm::schemagen::property<&TonalDBTuning::author, false> const&, realm::schemagen::property<&TonalDBTuning::period, false> const&, realm::schemagen::property<&TonalDBTuning::pitches, false> const&, realm::schemagen::property<&TonalDBTuning::mapping, false> const&, realm::schemagen::property<&TonalDBTuning::ownerId, false> const&>(auto&&...) const db.hpp:84
decltype(std::declval<TonalDBTuning>()(std::declval<realm::schemagen::property<&TonalDBTuning::_id, false> const&>(), std::declval<realm::schemagen::property<&TonalDBTuning::title, false> const&>(), std::declval<realm::schemagen::property<&TonalDBTuning::shortTitle, false> const&>(), std::declval<realm::schemagen::property<&TonalDBTuning::description, false> const&>(), std::declval<realm::schemagen::property<&TonalDBTuning::author, false> const&>(), std::declval<realm::schemagen::property<&TonalDBTuning::period, false> const&>(), std::declval<realm::schemagen::property<&TonalDBTuning::pitches, false> const&>(), std::declval<realm::schemagen::property<&TonalDBTuning::mapping, false> const&>(), std::declval<realm::schemagen::property<&TonalDBTuning::ownerId, false> const&>())) std::__1::__invoke[abi:v15006]<realm::experimental::managed<std::__1::remove_const<TonalDBTuning>::type, void> realm::experimental::db::add<TonalDBTuning>(TonalDBTuning&&)::'lambda'(auto&&...), realm::schemagen::property<&TonalDBTuning::_id, false> const&, realm::schemagen::property<&TonalDBTuning::title, false> const&, realm::schemagen::property<&TonalDBTuning::shortTitle, false> const&, realm::schemagen::property<&TonalDBTuning::description, false> const&, realm::schemagen::property<&TonalDBTuning::author, false> const&, realm::schemagen::property<&TonalDBTuning::period, false> const&, realm::schemagen::property<&TonalDBTuning::pitches, false> const&, realm::schemagen::property<&TonalDBTuning::mapping, false> const&, realm::schemagen::property<&TonalDBTuning::ownerId, false> const&>(TonalDBTuning&&, realm::schemagen::property<&TonalDBTuning::_id, false> const&, realm::schemagen::property<&TonalDBTuning::title, false> const&, realm::schemagen::property<&TonalDBTuning::shortTitle, false> const&, realm::schemagen::property<&TonalDBTuning::description, false> const&, realm::schemagen::property<&TonalDBTuning::author, false> const&, realm::schemagen::property<&TonalDBTuning::period, false> const&, realm::schemagen::property<&TonalDBTuning::pitches, false> const&, realm::schemagen::property<&TonalDBTuning::mapping, false> const&, realm::schemagen::property<&TonalDBTuning::ownerId, false> const&) invoke.h:394
decltype(auto) std::__1::__apply_tuple_impl[abi:v15006]<realm::experimental::managed<std::__1::remove_const<TonalDBTuning>::type, void> realm::experimental::db::add<TonalDBTuning>(TonalDBTuning&&)::'lambda'(auto&&...), std::__1::tuple<realm::schemagen::property<&TonalDBTuning::_id, false>, realm::schemagen::property<&TonalDBTuning::title, false>, realm::schemagen::property<&TonalDBTuning::shortTitle, false>, realm::schemagen::property<&TonalDBTuning::description, false>, realm::schemagen::property<&TonalDBTuning::author, false>, realm::schemagen::property<&TonalDBTuning::period, false>, realm::schemagen::property<&TonalDBTuning::pitches, false>, realm::schemagen::property<&TonalDBTuning::mapping, false>, realm::schemagen::property<&TonalDBTuning::ownerId, false>> const&, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul>(TonalDBTuning&&, std::__1::tuple<realm::schemagen::property<&TonalDBTuning::_id, false>, realm::schemagen::property<&TonalDBTuning::title, false>, realm::schemagen::property<&TonalDBTuning::shortTitle, false>, realm::schemagen::property<&TonalDBTuning::description, false>, realm::schemagen::property<&TonalDBTuning::author, false>, realm::schemagen::property<&TonalDBTuning::period, false>, realm::schemagen::property<&TonalDBTuning::pitches, false>, realm::schemagen::property<&TonalDBTuning::mapping, false>, realm::schemagen::property<&TonalDBTuning::ownerId, false>> const&, std::__1::__tuple_indices<0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul, 7ul, 8ul>) tuple:1789
decltype(auto) std::__1::apply[abi:v15006]<realm::experimental::managed<std::__1::remove_const<TonalDBTuning>::type, void> realm::experimental::db::add<TonalDBTuning>(TonalDBTuning&&)::'lambda'(auto&&...), std::__1::tuple<realm::schemagen::property<&TonalDBTuning::_id, false>, realm::schemagen::property<&TonalDBTuning::title, false>, realm::schemagen::property<&TonalDBTuning::shortTitle, false>, realm::schemagen::property<&TonalDBTuning::description, false>, realm::schemagen::property<&TonalDBTuning::author, false>, realm::schemagen::property<&TonalDBTuning::period, false>, realm::schemagen::property<&TonalDBTuning::pitches, false>, realm::schemagen::property<&TonalDBTuning::mapping, false>, realm::schemagen::property<&TonalDBTuning::ownerId, false>> const&>(TonalDBTuning&&, std::__1::tuple<realm::schemagen::property<&TonalDBTuning::_id, false>, realm::schemagen::property<&TonalDBTuning::title, false>, realm::schemagen::property<&TonalDBTuning::shortTitle, false>, realm::schemagen::property<&TonalDBTuning::description, false>, realm::schemagen::property<&TonalDBTuning::author, false>, realm::schemagen::property<&TonalDBTuning::period, false>, realm::schemagen::property<&TonalDBTuning::pitches, false>, realm::schemagen::property<&TonalDBTuning::mapping, false>, realm::schemagen::property<&TonalDBTuning::ownerId, false>> const&) tuple:1798
realm::experimental::db::add<…>(TonalDBTuning &&) db.hpp:83
<lambda>::operator()() const TonalDB.cpp:187
realm::experimental::db::write<…>(<lambda> &&) const db.hpp:66
...
```

**Comment by adamski** [comment] 2023-11-21 22:47
So after refactoring to replace the `realm::mixed` type I don't think that is the problem. I think it's related to how I am creating Realm objects on the heap and adding pointers to a vector. For example

```cpp
struct TonalDBKey
{
    // Note: Here degree is optional since we can't have a vector of optional types in Realm.
    // Instead we make it optional within the struct.
    std::optional<int64_t> degree = std::nullopt;
    int64_t                period = 0;
};
REALM_EMBEDDED_SCHEMA (TonalDBKey, degree, period)

//...


        for (const auto& key : publicTuning.mapping.keyMap)
        {
            TonalDBKey* dbKey;
            if (key.has_value())
            {
                dbKey = new TonalDBKey { static_cast<int64_t> (key.value().degree), static_cast<int64_t> (key.value().period) };
            }
            else
            {
                dbKey = new TonalDBKey { std::nullopt, 0 };
            }
            dbTuning.mapping->keyMap.push_back (dbKey);
        }
```

**Comment by adamski** [comment] 2023-11-21 23:24
It seems that the nesting was the issue. If I remove the `mapping` object which contained the vector, and have everything flat in one object then I don't get the crash.

**Comment by adamski** [comment] 2023-11-26 16:05
Related to #119

**Comment by leemaguire** [comment] 2023-11-29 08:02
@adamski Can you try this so to not allocate on the heap. If this doesn't solve it can you attach a code sample that I can run that reproduces the issue which you see.

```cpp
for (const auto& key : publicTuning.mapping.keyMap)
        {
            TonalDBKey dbKey;
            if (key.has_value())
            {
                dbKey = TonalDBKey { static_cast<int64_t> (key.value().degree), static_cast<int64_t> (key.value().period) };
            }
            else
            {
                dbKey = TonalDBKey { std::nullopt, 0 };
            }
            dbTuning.mapping->keyMap.push_back (&dbKey);
        }
```

**Comment by kneth** [comment] 2024-02-09 10:39
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.

**Closed by kneth** 2024-02-09 10:39 UTC
Labels: O-Community
