### ISSUE TITLE
Crash when using nested object with fresh database

### ISSUE THREAD

**Issue by adamski** [realm/realm-cpp#119] opened 2023-11-23 21:42 UTC
#### SDK and version
SDK : C++
Version: 0.4.0

#### Observations
* How frequent do the crash occur? When first generating the schema
* Does it happen in production or during dev/test? Debug
* Can the crash be reproduced by you? Yes
* Can you provide instructions for how we can reproduce it? Yes

#### Crash log / stacktrace
```
[realm-core-13.23.1] Assertion failed: type == ColumnTypeTraits<T>::column_id
0   Entonal Studio                      0x0000000105b36960 _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1   Entonal Studio                      0x0000000105b36940 _ZN5realm4util19terminate_with_infoEPKcS2_lS2_OSt16initializer_listINS0_9PrintableEE + 308
2   Entonal Studio                      0x0000000105b3680c _ZN5realm4util19terminate_with_infoEPKcS2_lS2_OSt16initializer_listINS0_9PrintableEE + 0
3   Entonal Studio                      0x0000000105a00814 _ZNK5realm3Obj3getINS_10StringDataEEET_NS_6ColKeyE + 140
4   Entonal Studio                      0x0000000105169ca0 _ZN5realm8internal6bridge3getINSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEET_RKNS1_3objERKNS1_7col_keyE + 68
5   Entonal Studio                      0x00000001051505a4 _ZNK5realm8internal6bridge3obj3getINSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEEET_RKNS1_7col_keyE + 40
6   Entonal Studio                      0x000000010515239c _ZNK5realm12experimental7managedINSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvE3getEv + 40
7   Entonal Studio                      0x0000000105152adc _ZNK5realm12experimental7managedINSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEvE6detachEv + 32
8   Entonal Studio                      0x000000010510fbb0 _ZZNK5realm12experimental7managedIP14TonalDBMappingvE6detachEvENKUlRT_E_clINSt3__14pairINS_9schemagen8propertyIXadL_ZNS2_10noteLayoutEEELb0EEEMNS1_IS2_vEENS1_INS9_12basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEEvEEEEEEDaS6_ + 56
9   Entonal Studio                      0x000000010510fadc _ZZNK5realm12experimental7managedIP14TonalDBMappingvE6detachEvENKUlDpOT_E_clIJRNSt3__14pairINS_9schemagen8propertyIXadL_ZNS2_12customKeyMapEEELb0EEEMNS1_IS2_vEENS1_IbvEEEERNSB_INSD_IXadL_ZNS2_10noteLayoutEEELb0EEEMSF_NS1_INSA_12basic_stringIcNSA_11char_traitsIcEENSA_9allocatorIcEEEEvEEEERNSB_INSD_IXadL_ZNS2_13referenceNoteEEELb0EEEMSF_NS1_IxvEEEERNSB_INSD_IXadL_ZNS2_18referenceFrequencyEEELb0EEEMSF_NS1_IdvEEEERNSB_INSD_IXadL_ZNS2_8rootNoteEEELb0EEESX_EERNSB_INSD_IXadL_ZNS2_6keyMapEEELb0EEEMSF_NS1_INSA_6vectorIP10TonalDBKeyNSO_IS1B_EEEEvEEEEEEEDaS7_ + 76
10  Entonal Studio                      0x000000010510f998 _ZNSt3__18__invokeB6v15006IZNK5realm12experimental7managedIP14TonalDBMappingvE6detachEvEUlDpOT_E_JRNS_4pairINS1_9schemagen8propertyIXadL_ZNS4_12customKeyMapEEELb0EEEMNS3_IS4_vEENS3_IbvEEEERNSB_INSD_IXadL_ZNS4_10noteLayoutEEELb0EEEMSF_NS3_INS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEvEEEERNSB_INSD_IXadL_ZNS4_13referenceNoteEEELb0EEEMSF_NS3_IxvEEEERNSB_INSD_IXadL_ZNS4_18referenceFrequencyEEELb0EEEMSF_NS3_IdvEEEERNSB_INSD_IXadL_ZNS4_8rootNoteEEELb0EEESX_EERNSB_INSD_IXadL_ZNS4_6keyMapEEELb0EEEMSF_NS3_INS_6vectorIP10TonalDBKeyNSO_IS1B_EEEEvEEEEEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOS1I_DpOS1J_ + 72
11  Entonal Studio                      0x000000010510f944 _ZNSt3__118__apply_tuple_implB6v15006IZNK5realm12experimental7managedIP14TonalDBMappingvE6detachEvEUlDpOT_E_RNS_5tupleIJNS_4pairINS1_9schemagen8propertyIXadL_ZNS4_12customKeyMapEEELb0EEEMNS3_IS4_vEENS3_IbvEEEENSC_INSE_IXadL_ZNS4_10noteLayoutEEELb0EEEMSG_NS3_INS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEvEEEENSC_INSE_IXadL_ZNS4_13referenceNoteEEELb0EEEMSG_NS3_IxvEEEENSC_INSE_IXadL_ZNS4_18referenceFrequencyEEELb0EEEMSG_NS3_IdvEEEENSC_INSE_IXadL_ZNS4_8rootNoteEEELb0EEESW_EENSC_INSE_IXadL_ZNS4_6keyMapEEELb0EEEMSG_NS3_INS_6vectorIP10TonalDBKeyNSO_IS17_EEEEvEEEEEEEJLm0ELm1ELm2ELm3ELm4ELm5EEEEDcOT_OT0_NS_15__tuple_indicesIJXspT1_EEEE + 128
12  Entonal Studio                      0x000000010510de88 _ZNSt3__15applyB6v15006IZNK5realm12experimental7managedIP14TonalDBMappingvE6detachEvEUlDpOT_E_RNS_5tupleIJNS_4pairINS1_9schemagen8propertyIXadL_ZNS4_12customKeyMapEEELb0EEEMNS3_IS4_vEENS3_IbvEEEENSC_INSE_IXadL_ZNS4_10noteLayoutEEELb0EEEMSG_NS3_INS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEvEEEENSC_INSE_IXadL_ZNS4_13referenceNoteEEELb0EEEMSG_NS3_IxvEEEENSC_INSE_IXadL_ZNS4_18referenceFrequencyEEELb0EEEMSG_NS3_IdvEEEENSC_INSE_IXadL_ZNS4_8rootNoteEEELb0EEESW_EENSC_INSE_IXadL_ZNS4_6keyMapEEELb0EEEMSG_NS3_INS_6vectorIP10TonalDBKeyNSO_IS17_EEEEvEEEEEEEEEDcOT_OT0_ + 32
13  Entonal Studio                      0x000000010510dd10 _ZNK5realm12experimental7managedIP14TonalDBMappingvE6detachEv + 288
14  Entonal Studio                      0x000000010510c430 _ZZNK5realm12experimental7managedI13TonalDBTuningvE6detachEvENKUlRT_E_clINSt3__14pairINS_9schemagen8propertyIXadL_ZNS2_7mappingEEELb0EEEMS3_NS1_IP14TonalDBMappingvEEEEEEDaS5_ + 48
15  Entonal Studio                      0x000000010510c07c _ZZNK5realm12experimental7managedI13TonalDBTuningvE6detachEvENKUlDpRT_E_clIJNSt3__14pairINS_9schemagen8propertyIXadL_ZNS2_3_idEEELb0EEEMS3_NS1_INS0_11primary_keyINS_4uuidEEEvEEEENSA_INSC_IXadL_ZNS2_9createdAtEEELb0EEEMS3_NS1_INS9_6chrono10time_pointINSL_12system_clockENSL_8durationIxNS9_5ratioILl1ELl1000000EEEEEEEvEEEENSA_INSC_IXadL_ZNS2_9updatedAtEEELb0EEESU_EENSA_INSC_IXadL_ZNS2_5titleEEELb0EEEMS3_NS1_INS9_12basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEEvEEEENSA_INSC_IXadL_ZNS2_10shortTitleEEELb0EEES16_EENSA_INSC_IXadL_ZNS2_11descriptionEEELb0EEES16_EENSA_INSC_IXadL_ZNS2_6authorEEELb0EEES16_EENSA_INSC_IXadL_ZNS2_6periodEEELb0EEES16_EENSA_INSC_IXadL_ZNS2_7pitchesEEELb0EEEMS3_NS1_INS9_6vectorIP12TonalDBPitchNS12_IS1J_EEEEvEEEENSA_INSC_IXadL_ZNS2_7mappingEEELb0EEEMS3_NS1_IP14TonalDBMappingvEEEENSA_INSC_IXadL_ZNS2_7ownerIdEEELb0EEEMS3_NS1_INS9_8optionalIS14_EEvEEEEEEEDaS6_ + 240
16  Entonal Studio                      0x000000010510bdcc _ZNSt3__18__invokeB6v15006IZNK5realm12experimental7managedI13TonalDBTuningvE6detachEvEUlDpRT_E_JRNS_4pairINS1_9schemagen8propertyIXadL_ZNS4_3_idEEELb0EEEMS5_NS3_INS2_11primary_keyINS1_4uuidEEEvEEEERNSA_INSC_IXadL_ZNS4_9createdAtEEELb0EEEMS5_NS3_INS_6chrono10time_pointINSM_12system_clockENSM_8durationIxNS_5ratioILl1ELl1000000EEEEEEEvEEEERNSA_INSC_IXadL_ZNS4_9updatedAtEEELb0EEESV_EERNSA_INSC_IXadL_ZNS4_5titleEEELb0EEEMS5_NS3_INS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEvEEEERNSA_INSC_IXadL_ZNS4_10shortTitleEEELb0EEES19_EERNSA_INSC_IXadL_ZNS4_11descriptionEEELb0EEES19_EERNSA_INSC_IXadL_ZNS4_6authorEEELb0EEES19_EERNSA_INSC_IXadL_ZNS4_6periodEEELb0EEES19_EERNSA_INSC_IXadL_ZNS4_7pitchesEEELb0EEEMS5_NS3_INS_6vectorIP12TonalDBPitchNS15_IS1R_EEEEvEEEERNSA_INSC_IXadL_ZNS4_7mappingEEELb0EEEMS5_NS3_IP14TonalDBMappingvEEEERNSA_INSC_IXadL_ZNS4_7ownerIdEEELb0EEEMS5_NS3_INS_8optionalIS17_EEvEEEEEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOS2C_DpOS2D_ + 148
17  Entonal Studio                      0x000000010510bd2c _ZNSt3__118__apply_tuple_implB6v15006IZNK5realm12experimental7managedI13TonalDBTuningvE6detachEvEUlDpRT_E_RNS_5tupleIJNS_4pairINS1_9schemagen8propertyIXadL_ZNS4_3_idEEELb0EEEMS5_NS3_INS2_11primary_keyINS1_4uuidEEEvEEEENSB_INSD_IXadL_ZNS4_9createdAtEEELb0EEEMS5_NS3_INS_6chrono10time_pointINSM_12system_clockENSM_8durationIxNS_5ratioILl1ELl1000000EEEEEEEvEEEENSB_INSD_IXadL_ZNS4_9updatedAtEEELb0EEESV_EENSB_INSD_IXadL_ZNS4_5titleEEELb0EEEMS5_NS3_INS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEvEEEENSB_INSD_IXadL_ZNS4_10shortTitleEEELb0EEES17_EENSB_INSD_IXadL_ZNS4_11descriptionEEELb0EEES17_EENSB_INSD_IXadL_ZNS4_6authorEEELb0EEES17_EENSB_INSD_IXadL_ZNS4_6periodEEELb0EEES17_EENSB_INSD_IXadL_ZNS4_7pitchesEEELb0EEEMS5_NS3_INS_6vectorIP12TonalDBPitchNS13_IS1K_EEEEvEEEENSB_INSD_IXadL_ZNS4_7mappingEEELb0EEEMS5_NS3_IP14TonalDBMappingvEEEENSB_INSD_IXadL_ZNS4_7ownerIdEEELb0EEEMS5_NS3_INS_8optionalIS15_EEvEEEEEEEJLm0ELm1ELm2ELm3ELm4ELm5ELm6ELm7ELm8ELm9ELm10EEEEDcOT_OT0_NS_15__tuple_indicesIJXspT1_EEEE + 228
18  Entonal Studio                      0x000000010510aac4 _ZNSt3__15applyB6v15006IZNK5realm12experimental7managedI13TonalDBTuningvE6detachEvEUlDpRT_E_RNS_5tupleIJNS_4pairINS1_9schemagen8propertyIXadL_ZNS4_3_idEEELb0EEEMS5_NS3_INS2_11primary_keyINS1_4uuidEEEvEEEENSB_INSD_IXadL_ZNS4_9createdAtEEELb0EEEMS5_NS3_INS_6chrono10time_pointINSM_12system_clockENSM_8durationIxNS_5ratioILl1ELl1000000EEEEEEEvEEEENSB_INSD_IXadL_ZNS4_9updatedAtEEELb0EEESV_EENSB_INSD_IXadL_ZNS4_5titleEEELb0EEEMS5_NS3_INS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEvEEEENSB_INSD_IXadL_ZNS4_10shortTitleEEELb0EEES17_EENSB_INSD_IXadL_ZNS4_11descriptionEEELb0EEES17_EENSB_INSD_IXadL_ZNS4_6authorEEELb0EEES17_EENSB_INSD_IXadL_ZNS4_6periodEEELb0EEES17_EENSB_INSD_IXadL_ZNS4_7pitchesEEELb0EEEMS5_NS3_INS_6vectorIP12TonalDBPitchNS13_IS1K_EEEEvEEEENSB_INSD_IXadL_ZNS4_7mappingEEELb0EEEMS5_NS3_IP14TonalDBMappingvEEEENSB_INSD_IXadL_ZNS4_7ownerIdEEELb0EEEMS5_NS3_INS_8optionalIS15_EEvEEEEEEEEEDcOT_OT0_ + 32
19  Entonal Studio                      0x00000001050ef074 _ZNK5realm12experimental7managedI13TonalDBTuningvE6detachEv + 144
20  Entonal Studio                      0x00000001050f0e28 _ZNK7tonaldb7TonalDB10getTuningsEv + 316
21  Entonal Studio                      0x00000001044c4f58 _ZN8DatabaseC2EbRN7tonaldb7TonalDBE + 140
22  Entonal Studio                      0x00000001044c5dc8 _ZN8DatabaseC1EbRN7tonaldb7TonalDBE + 56
23  Entonal Studio                      0x0000000104678fe8 _ZNSt3__111make_uniqueB6v15006I8DatabaseJbRN7tonaldb7TonalDBEEEENS_11__unique_ifIT_E15__unique_singleEDpOT0_ + 60
24  Entonal Studio                      0x00000001046781fc _ZN27EntonalStudioAudioProcessorC2Ev + 2492
25  Entonal Studio                      0x0000000104679a4c _ZN27EntonalStudioAudioProcessorC1Ev + 28
26  Entonal Studio                      0x000000010467afe4 _Z18createPluginFilterv + 28
27  Entonal Studio                      0x00000001043e2460 _ZN4juce24createPluginFilterOfTypeENS_14AudioProcessor11WrapperTypeE + 28
28  Entonal Studio                      0x00000001043d7fec _ZN4juce22StandalonePluginHolder12createPluginEv + 32
29  Entonal Studio                      0x00000001043d73f4 _ZN4juce22StandalonePluginHolderC2EPNS_11PropertySetEbRKNS_6StringEPKNS_18AudioDeviceManager16AudioDeviceSetupERKNS_5ArrayINS0_12PluginInOutsENS_20DummyCriticalSectionELi0EEEb + 556
30  Entonal Studio                      0x00000001043d5944 _ZN4juce22StandalonePluginHolderC1EPNS_11PropertySetEbRKNS_6StringEPKNS_18AudioDeviceManager16AudioDeviceSetupERKNS_5ArrayINS0_12PluginInOutsENS_20DummyCriticalSectionELi0EEEb + 96
31  Entonal Studio                      0x00000001043d5654 _ZN4juce22StandaloneFilterWindowC2ERKNS_6StringENS_6ColourEPNS_11PropertySetEbS3_PKNS_18AudioDeviceManager16AudioDeviceSetupERKNS_5ArrayINS_22StandalonePluginHolder12PluginInOutsENS_20DummyCriticalSectionELi0EEEb + 444
32  Entonal Studio                      0x00000001043d538c _ZN4juce22StandaloneFilterWindowC1ERKNS_6StringENS_6ColourEPNS_11PropertySetEbS3_PKNS_18AudioDeviceManager16AudioDeviceSetupERKNS_5ArrayINS_22StandalonePluginHolder12PluginInOutsENS_20DummyCriticalSectionELi0EEEb + 132
33  Entonal Studio                      0x00000001043d237c _ZN4juce19StandaloneFilterApp12createWindowEv + 204
34  Entonal Studio                      0x00000001043d20d4 _ZN4juce19StandaloneFilterApp10initialiseERKNS_6StringE + 40
35  Entonal Studio                      0x0000000104cbdd08 _ZN4juce19JUCEApplicationBase13initialiseAppEv + 196
36  Entonal Studio                      0x00000001049e8d84 _ZN4juce15JUCEApplication13initialiseAppEv + 24
37  Entonal Studio                      0x0000000104cbda84 _ZN4juce19JUCEApplicationBase4mainEv + 300
38  Entonal Studio                      0x0000000104cbd900 _ZN4juce19JUCEApplicationBase4mainEiPPKc + 68
39  Entonal Studio                      0x00000001043d1cf8 main + 56
40  dyld                                0x00000001852fbf28 start + 2236
```

#### Steps & Code to Reproduce
I'll create a test project if required to reproduce the issue.

**Comment by leemaguire** [comment] 2023-11-24 02:31
Hi @adamski can you please attach sample code so that we can reproduce the issue.

**Comment by nicola-cab** [comment] 2023-11-24 09:50
This assertion `REALM_ASSERT(type == ColumnTypeTraits<T>::column_id);` is telling us that the type stored inside the database for the column key requested is different from the type traits associated to the type T used for fetching the value. I think the problem is there.

**Comment by jedelbo** [comment] 2023-11-24 14:17
Yes - you seem to be using `realm::Obj::get<realm::StringData>` on a property that is not a string.

**Comment by adamski** [comment] 2023-11-26 16:03
Thanks, that seems like a good clue. Will investigate.

**Comment by leemaguire** [comment] 2023-11-29 07:58
@adamski can you share your object models and some code so we can reproduce this on our side?

**Comment by adamski** [comment] 2023-12-02 09:02
I updated my schema and the issue has gone away. I tried to reproduce before with a demo project but didn’t manage to. I’ll have another go in the next week.

**Comment by nicola-cab** [comment] 2023-12-07 13:11
Am I wrong in saying that this is likely a problem with a Schema property mismatch? I think we could close this issue.

**Comment by adamski** [comment] 2023-12-09 20:30
@nicola-cab can you clarify what you mean by a Schema property mismatch?

**Closed** 2024-02-09 10:41 UTC
Labels: O-Community
